program ProgramasCasaFreitas;

uses
  uMain in 'uMain.pas' {fmMain},
  uDm in '..\Funcoes\uDM\uDm.pas' {dm: TDataModule},
  aAjChNfe in 'fmAjChNfe\aAjChNfe.pas' {fmAjChaveNFe},
  adm in 'uAdm\adm.pas',
  cf in 'uCF\cf.pas',
  fdt in '..\Funcoes\fdt.pas',
  fmAbrirAvarias in 'fmAvarias\fmAbrirAvarias.pas' {fmAbrirAvaria},
  fmMudaSerieNota in 'fmMudaSerieNota\fmMudaSerieNota.pas' {fmAjustaSerie},
  f in '..\Funcoes\f.pas',
  funcSQL in '..\Funcoes\funcSQL.pas',
  msg in '..\Funcoes\msg.pas',
  uAbreMovDiario in '..\Funcoes\uAbreMovDiario.pas' {fmDialogMov},
  uAcbr in 'uAcbr\uAcbr.pas',
  uAjustaNota in 'fmAjustaNota\uAjustaNota.pas' {fmAjustaNota},
  uAjusteModPag in 'fmAjusteModPag\uAjusteModPag.pas',
  uAlteraFinanceira in 'fmAlteraFinanceira\uAlteraFinanceira.pas' {fmAlteraFiananceira},
  uAlteraForPedido in 'fmAlterafornecedorPedido\UAlteraForPedido.pas' {fmAlteraPedForn},
  uAlteraModalidadePagto in 'fmRemoveRegTEF\uAlteraModalidadePagto.pas' {fmAlteraModPagto},
  uAnaliseEstoque in 'fmAnaliseEstoque\uAnaliseEstoque.pas' {fmAnaliseEstoque},
  uAnaliseVenda in 'fmAnaliseVenda\uAnaliseVenda.pas' {fmFaturamento},
  uAprovaAvaria in 'fmAvarias\uAprovaAvaria.pas' {fmAprovaAv},
  uAutorizacao in '..\Funcoes\autorizacoes\uAutorizacao.pas',
  uAvarias in 'fmAvarias\uAvarias.pas' {fmCadAvarias},
  uBuscaCidade in 'fmBuscaCidade\uBuscaCidade.pas' {fmBuscaDiversas},
  uCadastrarNCM in 'fmCadastrarNCM\uCadastrarNCM.pas' {fmCadastraNCM},
  uCadBairro in 'fmCadBairro\uCadBairro.pas' {fmCadBairro},
  uCadImagem in 'fmCadImagem\uCadImagem.pas' {fmCadastro},
  uCadImpNFE in 'fmCadastraImpNFE\uCadImpNFE.pas' {fmCadImpNFE},
  uCargaVendas in 'fmCargaDados\uCargaVendas.pas' {fmCargaVendas},
  uCartoes in 'uCartoes\uCartoes.pas',
  uCategoria in 'fmCategorias\uCategoria.pas',
  uCEP in 'fmCEP\uCEP.pas' {fmCep},
  uCF in 'uCF\uCF.pas',
  uClassificaProd in 'fmClassificaProd\uClassificaProd.pas' {fmClassificaProd},
  uCmd in '..\Funcoes\uCmd\uCmd.pas',
  uCompFornecedor in 'fmCompFornecedor\uCompFornecedor.pas' {fmCompFornecedor},
  uComporEstoque in 'fmComporEstoque\uComporEstoque.pas' {fmComporEstoque},
  uConReqDep in 'requisicoes\fmReqPorLoja\uConReqDep.pas',
  uConReqProd in 'fmConREqProd\uConReqProd.pas' {fmConReqProduto},
  uConsultaPedCompra in 'fmconsultaPedidoCompra\uConsultaPedCompra.pas' {fmConsultaPedCompra},
  uContabil in 'uContabil\uContabil.pas',
  uCredCli in 'fmCredCliente\uCredCli.pas',
  uCredCliente in 'uCredCliente\uCredCliente.pas' {fmCredCliente},
  uCriaAvaria in 'fmAvarias\uCriaAvaria.pas' {fmCriarAvaria},
  uCriaMapa in 'fmMapaSeparacao\uCriaMapa.pas' {fmCriarMapa},
  uCriaReqFromPed in 'fmCriaReqFromPed\uCriaReqFromPed.pas' {fmCriaReqFromPed},
  uCustoPorPedido in 'fmListaPrecosCustoPorNota\uCustoPorPedido.pas' {fmCustoPorPedido},
  uDescPedido in 'fmDescontoPedido\uDescPedido.pas' {fmDescPed},
  uDestinoEmail in '..\Funcoes\uDestinoEmail.pas' {fmDestEmail},
  uDetalhesCRUC in 'fmGeraEstoque\fmDetalhesCRUC\uDetalhesCRUC.pas' {fmDetalhesCRUC},
  uDetalhesNotas in 'fmDetalhesNotas\uDetalhesNotas.pas' {fmDetalhesNota},
  uDetEntrada in 'fmDetalhesEntrada\uDetEntrada.pas' {fmDetEntrada},
  uDirDialog in '..\Funcoes\uDirDialog.pas' {fmDirDialog},
  uenviaEmail in 'fmEmail\uenviaEmail.pas' {fmEnviaEmail},
  uEstoque in 'uEstoque\uEstoque.pas',
  uEtiquetas in 'fmEtiquetas\uEtiquetas.pas' {fmEtiquetas},
  uetqNotas in 'fmPrecoCusto\uetqNotas.pas' {fmEtq},
  uExportaPedido in 'fmExportaPedido\uExportaPedido.pas' {fmExportaPedido},
  uExportaTable in 'fmGeraEstoque\fmExportacao\uExportaTable.pas' {fmExportaTable},
  uFiscal in 'uFiscal\uFiscal.pas',
  uFluxoClientes in 'uFluxoClientes\uFluxoClientes.pas' {fmVdPorHora},
  ufmAutorizacao in '..\Funcoes\autorizacoes\ufmAutorizacao.pas' {fmAutorizacao},
  uFmFtp in 'uFTP\uFmFtp.pas' {fmFTP},
  ufmMovDiario in 'fmMovDiario\ufmMovDiario.pas' {fmMovDiario},
  ufmTelnet in 'fmTelnet\ufmTelnet.pas' {fmTelnet},
  ufornACriticar in 'FmFornecACriticar\ufornACriticar.pas' {fmFornACriticar},
  uFtp in 'uFtp\uFtp.pas',
  uGeraEstoque in 'fmGeraEstoque\uGeraEstoque.pas' {fmGeraEstoque},
  uGuia in 'fmGuia\uGuia.pas' {fmGuia},
  uImpPedForn in 'uImpPedForn\uImpPedForn.pas' {fmImpPedForn},
  uImpXmlEnt in 'fmImpXmlEnt\uImpXmlEnt.pas' {fmImpXmlEnt},
  uInputData in '..\Funcoes\uInputData.pas' {fmInputData},
  uListaFornecedores in 'FmFornecACriticar\uListaFornecedores.pas' {fmListaFornecedores},
  uListaImpNFE in 'fmCadastraImpNFE\uListaImpNFE.pas' {fmListaImpNFE},
  uListaItensPorNota in 'fmPrecos\fmListaItensNotas\uListaItensPorNota.pas' {fmListaItensNota},
  uLj in '..\Funcoes\uLj\uLj.pas',
  uLogin in 'fmLogin\uLogin.pas',
  uLstPcAlt in 'fmPrecos\uLstPcAlt.pas' {fmLstPcAlt},
  uManutencaoCX in 'fmManutencaoCx\uManutencaoCX.pas' {fmManutencaoCX},
  uMapa in 'fmMapaSeparacao\uMapa.pas' {fmMapa},
  uMapaSep in 'fmMapaSeparacao\uMapaSep.pas',
  uMovDiario in 'fmMovDiario\uMovDiario.pas',
  unAjusteNumeracao in 'fmAjustaNumeracao\unAjusteNumeracao.pas' {fmAjustaNumNF},
  unClientes in 'fmEtiquetasClientes\unClientes.pas' {fmetqClientes},
  unNotasTransfrencia in 'fmRelNotasTransferidas\unNotasTransfrencia.pas' {fmNotasTransf},
  uNotasAgregadas in 'fmNotasAgregadas\uNotasAgregadas.pas' {fmNotasAgregadas},
  uNovaProposta in 'fmPropostas\uNovaProposta.pas' {fmNovaProposta},
  uObterSaldoFiscal in 'fmObterSaldoFiscal\uObterSaldoFiscal.pas' {fmObterSaldoFiscal},
  uOsDeposito in 'fmOsDeposito\uOsDeposito.pas' {fmOsDeposito},
  uPallet in 'fmEtiquetas\uPallet.pas' {Pallet},
  uParametros in 'fmParametros\uParametros.pas' {fmParametros},
  UpcoAlteradoPorPeriodo in 'fmPrecosAlteradosPorPeriodo\UpcoAlteradoPorPeriodo.pas' {fmPrecosAlterados},
  uPedCliente in 'uPedCliente\uPedCliente.pas',
  uPedFornecedor in 'uPedFornecedor\uPedFornecedor.pas',
  uPedidosFornecedor in 'fmGeraEstoque\fmPedidosFornecedor\uPedidosFornecedor.pas' {fmPedidosFornecedor},
  uPermissoes in 'fmPermissoes\uPermissoes.pas' {fmPermissoes},
  uPreco in 'uPreco\uPreco.pas',
  uPrecoPorPedido in 'fmPrecos\uPrecoPorPedido.pas',
  uPrecosCusto in 'fmPrecoCusto\uPrecosCusto.pas' {fmPrecoCustos},
  Uprecoswell in 'fmPrecos\Uprecoswell.pas' {fmLancaPc},
  uPropostaLoja in 'fmPropostas\uPropostaLoja.pas' {fmProposta},
  uReajuste in 'fmPrecos\uReajuste.pas' {fmReajuste},
  uRecibo in 'fmRecibo\uRecibo.pas' {fmRecibo},
  uRelatorioComissao in 'fmRelatorioComissao\uRelatorioComissao.pas' {fmRelatorioComissao},
  uRelGeral in 'fmRelatorioGeral\uRelGeral.pas' {fmRelGeral},
  uRelInventario in 'fmRelInventario\uRelInventario.pas' {fmRelInventario},
  uRelNotaTransf in 'fmRelNotasTransf\uRelNotaTransf.pas' {fmRelNotaTransf},
  uRelPedForn in 'fmRelPedForn\uRelPedForn.pas' {fmRelPedForn},
  uRemLancContabil in 'fmRemLancContabil\uRemLancContabil.pas' {fmRemLancContabil},
  uRemoveRegTEF in 'fmRemoveRegTEF\uRemoveRegTEF.pas' {fmRemRegTEF},
  uReq in 'uReqLojas\uReq.pas',
  uReqEmSeparacao in 'fmReqEmSeparacao\uReqEmSeparacao.pas' {fmReqEmSeparacao},
  uReqTransferidas in 'fmReqTransferidas\uReqTransferidas.pas' {fmReqTransferidas},
  urequisicao in 'uReqLojas\uRequisicao.pas' {fmReqLojas},
  uResumoECF in 'fmResumoECF\uResumoECF.pas' {fmResumoECF},
  uREsumoEstoque in 'fmResumoEstoque\uREsumoEstoque.pas' {fmResEstoque},
  uRotinasDiversas in 'fmRotinasDiversas\uRotinasDiversas.pas' {fmRotinasDiversas},
  uRRANA in 'fmRRANA\uRRANA.pas' {fmRelGeral1},
  uSelCat in 'fmCategorias\uSelCat.pas' {fmSelCat},
  uSelecionaUo in 'fmSelecionaUo\uSelecionaUo.pas' {fmSelecionaUo},
  uTabela in 'fmTabela\uTabela.pas' {fmTabela},
  uTabelaModal in 'fmTabela\uTabelaModal.pas' {fmTbModal},
  uTbPreco in 'fmTabela\uTbPreco.pas',
  uTelnet in 'fmTelnet\uTelnet.pas',
  uTipoImpGeraEstoque in 'fmGeraEstoque\fmTipoImpressao\uTipoImpGeraEstoque.pas' {fmTipoImpressaoGera},
  uTotalEntSai in 'fmGeraEstoque\fmTotalEntSai\uTotalEntSai.pas' {fmTotalEntSai},
  uTotalSaidas in 'fmTotalSaidas\uTotalSaidas.pas' {fmTotalSaidas},
  uUsuarios in 'uUsuarios\uUsuarios.pas',
  uWms in 'uWms\uWms.pas',
  uCaixa in 'uCaixa\uCaixa.pas',
  uAcertoEstoque in 'fmAcertoEst\uAcertoEstoque.pas' {fmAcertoEstoque},
  uProd in 'uProd\uProd.pas',
  ufmLstDrvEntSaiCD in 'fmLstDrvEntSaiCD\ufmLstDrvEntSaiCD.pas' {fmLstDrvEntSaiCD},
  uMsgMemoInput in '..\Funcoes\formsMsg\uMsgMemoInput.pas' {fmMsgMemoInput},
  uHash3F in '..\Funcoes\uHash3F.pas',
  uImpFichas in 'uContabil\uImpFichas.pas' {fmLstFichaCatCont},
  uLsdDrvgWellWms in 'uWms\uLsdDrvgWellWms.pas' {fmLsdDrvgWellWms},
  uRemReqPendente in 'fmRemReqPendentes\uRemReqPendente.pas' {fmRemItensSep},
  uVdBrutaIt in '..\fmVendaBrutaItens\uVdBrutaIt.pas' {fmVdBrutaIt},
  uModPag in 'fmAjusteModPag\uModPag.pas',
  uPessoa in 'uPessoa\uPessoa.pas',
  uEntUsaivdMed in 'uEntSaiVdMed\uEntUsaivdMed.pas' {fmDadosEntSaiMed},
  uDadosGeraEst in 'fmGeraEstoque\uDadosGeraEst.pas',
  ufmSelColImport in 'uProd\ufmSelColImport.pas' {fmSelColImport},
  uFmCriaNf in 'fmCriaNf\uFmCriaNf.pas' {fmCriaNf},
  uItensSemMov in 'fmItensSemMov\uItensSemMov.pas',
  AnaliseDeSaidaEstCd in 'fmAnaliseDeSaidaEstCd\AnaliseDeSaidaEstCd.pas' {fmAnEstCd},
  uRelCredCli in 'fmCredCliente\uRelCredCli.pas' {fmRelCredCli},
  uEtq in 'uEtq\uEtq.pas',
  uDescPorData in 'fmDescPorData\uDescPorData.pas' {fmDescPorData},
  uTroca in 'uImpTrocas\uTroca.pas',
  ufmImpTrocas in 'uImpTrocas\ufmImpTrocas.pas' {fmImpTroca},
  ufmAjCidades in 'uAjCidades\ufmAjCidades.pas' {fmAjCidades},
  uBuscasDiversas in 'uBuscDiversas\uBuscasDiversas.pas',
  uAjustaSPED in 'fmAjustaSPED\uAjustaSPED.pas' {fmAjustaSPED},
  uAddItOrc in 'fmAddItOrc\uAddItOrc.pas' {fmAddItOrc},
  uDadosAdTotvs in 'fmDadosAdTotvs\uDadosAdTotvs.pas' {fmDadosAdTotvs},
  uLstCustoDeVenda in 'fmLstCustoDeVenda\uLstCustoDeVenda.pas' {fmLstCustoDeVenda},
  windows,
  Forms,
  system,
  sysUtils,
  uSpedCont in 'spedCont\uSpedCont.pas' {fmSpedCont},
  rSped in 'spedCont\rSped.pas',
  uAdiantamento in 'uAdiantamento\uAdiantamento.pas';

{$R *.res}

const
   VERSAO = '15.12.01';
   SUB_VERSAO = '030';

begin
   if (f.getIdxParam('***') < 0 ) and (SysUtils.fileExists('upgrade.exe') ) then
   begin
      f.gravaLog('mudar para a aplicação:' + 'cmd /c Upgrade.exe'+ ' p1 ' + paramStr(0) +' -noUpgrade');
      winExec(pchar('cmd /c Upgrade.exe'+ ' p1 ' + ParamStr(0) +' -noUpgrade'  ), sw_hide);
      application.terminate;
	end
   else
   begin
      Application.Initialize;
		Application.Title := 'Programas Loja';
		Application.CreateForm(Tdm, dm);
  Application.CreateForm(TfmMain, fmMain);
  fmMain.versao.Caption := VERSAO;
      FMmAIN.sub_versao.caption := sub_versao;
      Application.Run;
   end;
end.

